### ISSUE TITLE
Closing wallet pop-up not caught for Leather

### ISSUE THREAD

**Issue by jordankzf** [ordzaar/ord-connect#242]
The error `Request canceled by user.` is thrown for Xverse, UniSat, and Magic Eden when the user selects a wallet, and closes the wallet pop-up connection request.

<img width="536" alt="image" src="https://github.com/ordzaar/ord-connect/assets/65149726/1e7059b1-6830-4317-b6d3-9d34536099a4">

However, for Leather, the ord-connect modal waits indefinitely.

<img width="525" alt="image" src="https://github.com/ordzaar/ord-connect/assets/65149726/ddba7ed1-e59f-4e32-87ef-fb273434bae9">

**Comment by thedoublejay** [comment]
Hello @jordankzf, we will attend to this issue 💯

**Comment by Nanosync** [comment]
This issue has been fixed by Leather.
